# Exploratory Data Analysis for Chronic Disease Indicator - COPD

In [4]:
# Imports
import pandas as pd

In [5]:
# Function to read the data
def read_data(file_path):
    return pd.read_csv(file_path)
path = '/home/daniel.lien/dev/homework/data/U.S._Chronic_Disease_Indicators_20250204.csv'
df = read_data(path)
print(df.shape) #(309215, 34)
# df.head()

(309215, 34)

In [6]:
#Check the Columns
df.columns

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'DataSource',
       'Topic', 'Question', 'Response', 'DataValueUnit', 'DataValueType',
       'DataValue', 'DataValueAlt', 'DataValueFootnoteSymbol',
       'DataValueFootnote', 'LowConfidenceLimit', 'HighConfidenceLimit',
       'StratificationCategory1', 'Stratification1', 'StratificationCategory2',
       'Stratification2', 'StratificationCategory3', 'Stratification3',
       'Geolocation', 'LocationID', 'TopicID', 'QuestionID', 'ResponseID',
       'DataValueTypeID', 'StratificationCategoryID1', 'StratificationID1',
       'StratificationCategoryID2', 'StratificationID2',
       'StratificationCategoryID3', 'StratificationID3'],
      dtype='object')

In [7]:
def check_unique_values(df):
    for col in df.columns:
        print(f'{col}: {df[col].unique()}')
        
# check_unique_values(df) #Save the output to a file for review

## Data Cleaning - Chronic Obstructive Pulmonary Disease (COPD)

In [8]:
# Drop Columns that are not needed or empty
df = df.drop(columns=['Response','ResponseID',
              'Stratification2','StratificationCategory2','StratificationID2','StratificationCategoryID2',
              'Stratification3', 'StratificationCategory3', 'StratificationID3','StratificationCategoryID3'])

# From 34 columns to 24 columns - correct
df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,...,HighConfidenceLimit,StratificationCategory1,Stratification1,Geolocation,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1
0,2019,2019,AR,Arkansas,BRFSS,Diabetes,Diabetes among adults,%,Crude Prevalence,13.6,...,15.4,Sex,Male,POINT (-92.27449074299966 34.74865012400045),5,DIA,DIA01,CRDPREV,SEX,SEXM
1,2019,2019,ID,Idaho,BRFSS,Diabetes,Diabetes among adults,%,Crude Prevalence,10.6,...,12.2,Sex,Male,POINT (-114.3637300419997 43.682630005000476),16,DIA,DIA01,CRDPREV,SEX,SEXM
2,2019,2019,IN,Indiana,YRBSS,Sleep,Short sleep duration among high school students,%,Crude Prevalence,NaN,...,NaN,Grade,Grade 12,POINT (-86.14996019399968 39.766910452000445),18,SLEP,SLP02,CRDPREV,GRADE,GRD12
3,2019,2019,IA,Iowa,NVSS,Asthma,"Asthma mortality among all people, underlying ...",Number,Number,54.0,...,NaN,Overall,Overall,POINT (-93.81649055599968 42.46940091300047),19,AST,AST01,NMBR,OVERALL,OVR
4,2019,2019,IA,Iowa,BRFSS,Asthma,Current asthma among adults,%,Crude Prevalence,10.3,...,11.7,Age,Age 18-44,POINT (-93.81649055599968 42.46940091300047),19,AST,AST02,CRDPREV,AGE,AGE1844

In [9]:
df_copd = df[df['Topic'] == 'Chronic Obstructive Pulmonary Disease']
print(df_copd.shape)
# df_copd.head()
# #(309215, 34) to (26951, 29) - about 8.7% of data is related to COPD

(26951, 24)

In [10]:
df_copd.isnull().sum()

YearStart                        0
YearEnd                          0
LocationAbbr                     0
LocationDesc                     0
DataSource                       0
Topic                            0
Question                         0
DataValueUnit                    0
DataValueType                    0
DataValue                     8614
DataValueAlt                  8614
DataValueFootnoteSymbol      18293
DataValueFootnote            18293
LowConfidenceLimit           13322
HighConfidenceLimit          13322
StratificationCategory1          0
Stratification1                  0
Geolocation                    509
LocationID                       0
TopicID                          0
QuestionID                       0
DataValueTypeID                  0
StratificationCategoryID1        0
StratificationID1                0
dtype: int64

In [11]:
#Drop more uncessary columns
"""
Data Value Alt (copy of data value)
Data Value Footnote 
Data Value Footnote Symbol (too many missing values)
Location Abbr (redundant) We are keeping location Desc
Location ID (redundant)
TopicID (we should only have COPD) --> confirmed print(df_copd["TopicID"].unique())
Data Value Type ID (we will use DataValueType)
"""
columns_to_drop = ['DataValueAlt', 'DataValueFootnoteSymbol', 'DataValueFootnote',
                   'LocationID', 'LocationAbbr', 'TopicID', 'DataValueTypeID']

df_copd = df_copd.drop(columns=columns_to_drop)

In [21]:
df_copd.isnull().sum()

YearStart                        0
YearEnd                          0
LocationDesc                     0
DataSource                       0
Topic                            0
Question                         0
DataValueUnit                    0
DataValueType                    0
DataValue                     8614
LowConfidenceLimit           13322
HighConfidenceLimit          13322
StratificationCategory1          0
Stratification1                  0
Geolocation                    509
QuestionID                       0
StratificationCategoryID1        0
StratificationID1                0
dtype: int64

In [12]:
# Last Check
df_copd.shape
df_copd.head()

,YearStart,YearEnd,LocationDesc,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,Geolocation,QuestionID,StratificationCategoryID1,StratificationID1
14201,2019,2019,Arizona,CMS Part A Claims Data,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,"cases per 1,000",Crude Rate,58.19,54.57,61.82,Race/Ethnicity,Hispanic,POINT (-111.76381127699972 34.865970280000454),COPD03,RACE,HIS
14214,2019,2019,Arizona,NVSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,"cases per 100,000",Age-adjusted Rate,NaN,NaN,NaN,Race/Ethnicity,"Hawaiian or Pacific Islander, non-Hispanic",POINT (-111.76381127699972 34.865970280000454),COPD05,RACE,HAPI
14217,2019,2019,Arizona,NVSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Number,Number,66.00,NaN,NaN,Race/Ethnicity,"American Indian or Alaska Native, non-Hispanic",POINT (-111.76381127699972 34.865970280000454),COPD06,RACE,AIAN
14222,2019,2019,California,NVSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Number,Number,58.00,NaN,NaN,Race/Ethnicity,"Hawaiian or Pacific Islander, non-Hispanic",POINT (-120.99999953799971 37.63864012300047),COPD06,RACE,HAPI
14243,2019,2019,Arkansas,BRFSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,%,Crude Prevalence,4.50,3.20,6.20,Age,Age 18-44,POINT (-92.27449074299966 34.74865012400045),COPD01,AGE,AGE1844

In [13]:
# Reset Index
df_copd.reset_index(drop=True, inplace=True)

In [14]:
#create a working copy
df = df_copd.copy()
print(df.shape)
df.head()

(26951, 17)

,YearStart,YearEnd,LocationDesc,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,Geolocation,QuestionID,StratificationCategoryID1,StratificationID1
0,2019,2019,Arizona,CMS Part A Claims Data,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,"cases per 1,000",Crude Rate,58.19,54.57,61.82,Race/Ethnicity,Hispanic,POINT (-111.76381127699972 34.865970280000454),COPD03,RACE,HIS
1,2019,2019,Arizona,NVSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,"cases per 100,000",Age-adjusted Rate,NaN,NaN,NaN,Race/Ethnicity,"Hawaiian or Pacific Islander, non-Hispanic",POINT (-111.76381127699972 34.865970280000454),COPD05,RACE,HAPI
2,2019,2019,Arizona,NVSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Number,Number,66.00,NaN,NaN,Race/Ethnicity,"American Indian or Alaska Native, non-Hispanic",POINT (-111.76381127699972 34.865970280000454),COPD06,RACE,AIAN
3,2019,2019,California,NVSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease mortalit...,Number,Number,58.00,NaN,NaN,Race/Ethnicity,"Hawaiian or Pacific Islander, non-Hispanic",POINT (-120.99999953799971 37.63864012300047),COPD06,RACE,HAPI
4,2019,2019,Arkansas,BRFSS,Chronic Obstructive Pulmonary Disease,Chronic obstructive pulmonary disease among ad...,%,Crude Prevalence,4.50,3.20,6.20,Age,Age 18-44,POINT (-92.27449074299966 34.74865012400045),COPD01,AGE,AGE1844

In [15]:
df['DataValueType'].unique()

array(['Crude Rate', 'Age-adjusted Rate', 'Number', 'Crude Prevalence',
       'Age-adjusted Prevalence'], dtype=object)

In [16]:
df['Question'].unique()

array(['Hospitalization for chronic obstructive pulmonary disease as any diagnosis, Medicare-beneficiaries aged 65 years and older',
       'Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying cause',
       'Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying or contributing cause',
       'Chronic obstructive pulmonary disease among adults',
       'Current smoking among adults with chronic obstructive pulmonary disease',
       'Hospitalization for chronic obstructive pulmonary disease as principal diagnosis, Medicare-beneficiaries aged 65 years and older'],
      dtype=object)

In [20]:
question_value_dict = df.groupby('Question')['DataValueType'].unique().apply(list).to_dict()

pd.DataFrame([(k, v) for k, v in question_value_dict.items()], columns=['Question', 'DataValueTypes'])

,Question,DataValueTypes
0,Chronic obstructive pulmonary disease among ad...,"[Crude Prevalence, Age-adjusted Prevalence]"
1,Chronic obstructive pulmonary disease mortalit...,"[Age-adjusted Rate, Number, Crude Rate]"
2,Chronic obstructive pulmonary disease mortalit...,"[Number, Crude Rate, Age-adjusted Rate]"
3,Current smoking among adults with chronic obst...,"[Crude Prevalence, Age-adjusted Prevalence]"
4,Hospitalization for chronic obstructive pulmon...,"[Crude Rate, Number, Age-adjusted Rate]"
5,Hospitalization for chronic obstructive pulmon...,"[Number, Crude Rate, Age-adjusted Rate]"