# Exploratory Data Analysis for Chronic Disease Indicator - All diseases

# Context
Chronic Disease Indicators provides data that tracks various chronic diseases and their risk factors at the national and state levels.
This dataset is a compliation of various data sources, including surveys, vital records, and administrative data.

## Data Dictionary:
- 'YearStart': Year the Survey/Collection began
- 'YearEnd': Year the Survey/Collection ended
- 'LocationAbbr': Two (2) letter abbreviation of the Location
- 'LocationDesc': Full name of the Location
- 'DataSource': Survey/Collection Source of the data
- 'Topic': Chronic Disease Topic
- 'Question': Question related to the Topic
- 'Response': Nan
- 'DataValueUnit': Response Value unit type
- 'DataValueType'" Response Value type
- 'DataValue': Response Value
- 'DataValueAlt': Alternate Response Value
- 'DataValueFootnoteSymbol': Footnote symbol
- 'DatavalueFootnote': Footnote 
- 'LowConfidenceLimit': Lowerbound confidence level
- 'HighConfidenceLimit': Higherbound confidence level
- 'StratificationCategory1': Stratification category for response
- 'Stratification1': Stratification grouping
- 'StratificationCategory2', Secondary Stratification category
- 'Stratification2', Seconday Stratification grouping
- 'StratificationCategory3': Tertiary Stratification Category
- 'Stratification3': Tertiary stratification grouping 
- 'GeoLocation': Geolocation ID Point(x,y) 
- 'ResponseID': Nan
- 'LocationID', Numerical representation of Location (1-78)
- 'TopicID': Topic ID Abbreviation
- 'QuestionID': Question ID Abbreviation 
- 'DataValueTypeID': ID Abbreviation for Data Value Type
- 'StratificationCategoryID1: Stratificaiton Category ID 
- 'StratificationID1', Stratification ID
- 'StratificationCategoryID2': NAN
- 'StratificationID2': NAN
- 'StratificationCategoryID3': NAN
- 'StratificationID3': NAN

In [130]:
# Imports
import pandas as pd

In [131]:
# Read in the Data
path = '/home/daniel.lien/dev/homework/data/U.S._Chronic_Disease_Indicators__CDI___2023_Release copy.csv'
def read_data(file_path):
    return pd.read_csv(file_path)
df_all = read_data(path)
df_all.head()

/tmp/ipykernel_734924/586502466.py:4: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(file_path)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2010,2010,OR,Oregon,NVSS,Cardiovascular Disease,Mortality from heart failure,NaN,NaN,Number,...,41,CVD,CVD1_4,NMBR,RACE,AIAN,NaN,NaN,NaN,NaN
1,2019,2019,AZ,Arizona,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,4,ALC,ALC1_1,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
2,2019,2019,OH,Ohio,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,39,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
3,2019,2019,US,United States,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,59,ALC,ALC1_1,CRDPREV,RACE,ASN,NaN,NaN,NaN,NaN
4,2015,2015,VI,Virgin Islands,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,78,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN

In [132]:
# Ensure csv is loaded by checking the shape of the Dataset
print(f"There are {df_all.shape[0]} rows and {df_all.shape[1]} cols in this large dataset")

There are 1185676 rows and 34 cols in this large dataset

In [133]:
# Check columns and datatypes
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1185676 entries, 0 to 1185675
Data columns (total 34 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   YearStart                  1185676 non-null  int64
 1   YearEnd                    1185676 non-null  int64
 2   LocationAbbr               1185676 non-null  object
 3   LocationDesc               1185676 non-null  object
 4   DataSource                 1185676 non-null  object
 5   Topic                      1185676 non-null  object
 6   Question                   1185676 non-null  object
 7   Response                   0 non-null        float64
 8   DataValueUnit              1033553 non-null  object
 9   DataValueType              1185676 non-null  object
 10  DataValue                  806942 non-null   object
 11  DataValueAlt               804578 non-null   float64
 12  DataValueFootnoteSymbol    393710 non-null   object
 13  DatavalueFootnote          393710 non-null   object
 14  LowConfidenceLimit         682380 non-null   float64
 15  HighConfidenceLimit        682380 non-null   float64
 16  StratificationCategory1    1185676 non-null  object
 17  Stratification1            1185676 non-null  object
 18  StratificationCategory2    0 non-null        float64
 19  Stratification2            0 non-null        float64
 20  StratificationCategory3    0 non-null        float64
 21  Stratification3            0 non-null        float64
 22  GeoLocation                1175510 non-null  object
 23  ResponseID                 0 non-null        float64
 24  LocationID                 1185676 non-null  int64
 25  TopicID                    1185676 non-null  object
 26  QuestionID                 1185676 non-null  object
 27  DataValueTypeID            1185676 non-null  object
 28  StratificationCategoryID1  1185676 non-null  object
 29  StratificationID1          1185676 non-null  object
 30  StratificationCategoryID2  0 non-null        float64
 31  StratificationID2          0 non-null        float64
 32  StratificationCategoryID3  0 non-null        float64
 33  StratificationID3          0 non-null        float64
dtypes: float64(13), int64(3), object(18)
memory usage: 307.6+ MB

In [134]:
# Check Unique Values for each column
def check_unique_values(df):
    for col in df.columns:
        print(f'{col}: {df[col].unique()}')
        
check_unique_values(df_all) #Save the output to a file for review

YearStart: [2010 2019 2015 2020 2018 2013 2011 2012 2016 2014 2017 2021 2009 2008
 2001 2007]
YearEnd: [2010 2019 2015 2020 2018 2013 2011 2012 2016 2014 2017 2021 2001 2008
 2009 2007]
LocationAbbr: ['OR' 'AZ' 'OH' 'US' 'VI' 'AL' 'DE' 'FL' 'KS' 'MS' 'NJ' 'PA' 'SD' 'VT'
 'AK' 'AR' 'CO' 'CT' 'DC' 'GA' 'HI' 'IA' 'ID' 'IN' 'KY' 'LA' 'MA' 'ME'
 'MI' 'MN' 'MO' 'MT' 'ND' 'NE' 'NH' 'NM' 'NV' 'NY' 'OK' 'RI' 'SC' 'TN'
 'TX' 'UT' 'VA' 'WA' 'WI' 'WV' 'WY' 'CA' 'NC' 'GU' 'IL' 'PR' 'MD']
LocationDesc: ['Oregon' 'Arizona' 'Ohio' 'United States' 'Virgin Islands' 'Alabama'
 'Delaware' 'Florida' 'Kansas' 'Mississippi' 'New Jersey' 'Pennsylvania'
 'South Dakota' 'Vermont' 'Alaska' 'Arkansas' 'Colorado' 'Connecticut'
 'District of Columbia' 'Georgia' 'Hawaii' 'Iowa' 'Idaho' 'Indiana'
 'Kentucky' 'Louisiana' 'Massachusetts' 'Maine' 'Michigan' 'Minnesota'
 'Missouri' 'Montana' 'North Dakota' 'Nebraska' 'New Hampshire'
 'New Mexico' 'Nevada' 'New York' 'Oklahoma' 'Rhode Island'
 'South Carolina' 'Tennessee' 'Texas' 'Utah' 'Virginia' 'Washington'
 'Wisconsin' 'West Virginia' 'Wyoming' 'California' 'North Carolina'
 'Guam' 'Illinois' 'Puerto Rico' 'Maryland']
DataSource: ['NVSS' 'YRBSS' 'PRAMS' 'BRFSS' 'SEDD; SID'
 'Statewide central cancer registries' 'Death Certificate' 'USRDS'
 'CMS Part A Claims Data' 'ACS 1-Year Estimates' 'CMS CCW' 'HRSA, UDS'
 'WFRS' 'NVSS, Mortality' 'Legal Research' 'APIS' 'AEDS'
 'Birth Certificate, NVSS' 'NSCH' 'Current Population Survey'
 'CDC Breastfeeding Report Card' 'CDC School Health Profiles'
 'National Immunization Survey' 'mPINC'
 "CDC Children's Food Environment State Indicator Report"
 "USDA National Farmers' Market Directory" 'InfoUSA; USDA' 'ASHW' 'STATE'
 'ACS 5-Year Estimates' 'ANRF']
Topic: ['Cardiovascular Disease' 'Alcohol' 'Arthritis' 'Asthma' 'Cancer'
 'Chronic Kidney Disease' 'Chronic Obstructive Pulmonary Disease'
 'Mental Health' 'Tobacco' 'Overarching Conditions' 'Oral Health'
 'Reproductive Health' 'Diabetes' 'Immunization'
 'Nutrition, Physical Activity, and Weight Status' 'Disability'
 'Older Adults']
Question: ['Mortality from heart failure' 'Alcohol use among youth'
 'Alcohol use before pregnancy' 'Binge drinking prevalence among youth'
 'Chronic liver disease mortality'
 'Adults aged >= 18 years with arthritis who have taken a class to learn how to manage arthritis symptoms'
 'Arthritis among adults aged >= 18 years who are obese'
 'Emergency department visit rate for asthma'
 'Hospitalizations for asthma' 'Asthma mortality rate'
 'Invasive cancer of the oral cavity or pharynx, incidence'
 'Cancer of the oral cavity and pharynx, mortality'
 'Invasive cancer of the prostate, incidence'
 'Cancer of the prostate, mortality'
 'Invasive cancer (all sites combined), incidence'
 'Invasive cancer (all sites combined), mortality'
 'Invasive cancer of the female breast, incidence' 'Melanoma, mortality'
 'Cancer of the female breast, mortality'
 'Invasive cancer of the cervix, incidence'
 'Cancer of the female cervix, mortality'
 'Cancer of the colon and rectum (colorectal), incidence'
 'Cancer of the colon and rectum (colorectal), mortality'
 'Cancer of the lung and bronchus, incidence'
 'Cancer of the lung and bronchus, mortality'
 'Invasive melanoma, incidence' 'Mortality with end-stage renal disease'
 'Incidence of treated end-stage renal disease'
 'Incidence of treated end-stage renal disease attributed to diabetes'
 'Mortality with chronic obstructive pulmonary disease as underlying cause among adults aged >= 45 years'
 'Mortality from coronary heart disease'
 'At least 14 recent mentally unhealthy days among women aged 18-44 years'
 'Arthritis among adults aged >= 18 years who have diabetes'
 'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years who smoke'
 'Arthritis among adults aged >= 18 years'
 'Quit attempts in the past year among current smokers'
 'Binge drinking frequency among adults aged >= 18 years who binge drink'
 'Recent activity limitation among adults aged >= 18 years'
 'High cholesterol prevalence among adults aged >= 18 years'
 'Current cigarette smoking among women aged 18-44 years'
 'Physical inactivity among adults aged >= 18 years with arthritis'
 'Mortality with chronic obstructive pulmonary disease as underlying or contributing cause among adults aged >= 45 years'
 'Prevalence of sufficient sleep among adults aged >= 18 years'
 'Binge drinking prevalence among women aged 18-44 years'
 'Binge drinking intensity among adults aged >= 18 years who binge drink'
 'Fair or poor health among adults aged >= 18 years with arthritis'
 'Binge drinking prevalence among adults aged >= 18 years'
 'Fecal occult blood test, sigmoidoscopy, or colonoscopy among adults aged 50-75 years'
 'Current health care coverage among women aged 18-44 years'
 'Recent physically unhealthy days among adults aged >= 18 years'
 'Six or more teeth lost among adults aged >= 65 years'
 'Current smoking among adults aged >= 18 years'
 'Heavy drinking among adults aged >= 18 years'
 'Timeliness of routine health care checkup among women aged 18-44 years'
 'Prevalence of diagnosed diabetes among adults aged >= 18 years'
 'Recent mentally unhealthy days among adults aged >= 18 years'
 'Cholesterol screening among adults aged >= 18 years'
 'Visits to dentist or dental clinic among adults aged >= 18 years with diagnosed diabetes'
 'Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis'
 'Arthritis among adults aged >= 18 years who have heart disease'
 'Hospitalization for chronic obstructive pulmonary disease as any diagnosis'
 'Heavy drinking among women aged 18-44 years'
 'Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis among Medicare-eligible persons aged >= 65 years'
 'Visits to dentist or dental clinic among adults aged >= 18 years'
 'Influenza vaccination among noninstitutionalized adults aged >= 65 years with asthma'
 'All teeth lost among adults aged >= 65 years'
 'Influenza vaccination among noninstitutionalized adults aged >= 18 years'
 'Foot examination among adults aged >= 18 years with diagnosed diabetes'
 'Fair or poor self-rated health status among adults aged >= 18 years'
 'Prevalence of high cholesterol among adults aged >= 18 years with diagnosed diabetes'
 'Influenza vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes'
 'Influenza vaccination among noninstitutionalized adults aged 18-64 years with asthma'
 'Influenza vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes'
 'Awareness of high blood pressure among women aged 18-44 years'
 'Healthy weight among adults aged >= 18 years'
 'Awareness of high blood pressure among adults aged >= 18 years'
 'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes'
 'Prevalence of chronic kidney disease among adults aged >= 18 years'
 'Current lack of health insurance among adults aged 18-64 years'
 'Hospitalization for chronic obstructive pulmonary disease as any diagnosis among Medicare-eligible persons aged >= 65 years'
 'Dilated eye examination among adults aged >= 18 years with diagnosed diabetes'
 'Mortality from total cardiovascular diseases'
 'Mammography use among women aged 50-74 years'
 'Overweight or obesity among women aged 18-44 years'
 'Papanicolaou smear use among adult women aged 21-65 years'
 'Work limitation due to arthritis among adults aged 18-64 years who have doctor-diagnosed arthritis'
 'Prevalence of depressive disorders among adults aged >= 18 years with diagnosed diabetes'
 'Glycosylated hemoglobin measurement among adults aged >= 18 years with diagnosed diabetes'
 'Overweight or obesity among adults aged >= 18 years'
 'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with asthma'
 'Emergency department visit rate for chronic obstructive pulmonary disease as first-listed diagnosis'
 'Self-rated health status among women aged 18-44 years'
 'Emergency department visit rate for chronic obstructive pulmonary disease as any diagnosis'
 'No tooth loss among adults aged 18-64 years'
 'No leisure-time physical activity among adults aged >= 18 years'
 'Obesity among adults aged >= 18 years'
 'Recent Papanicolaou smear use among women aged 21-44 years'
 'Current asthma prevalence among adults aged >= 18 years'
 'Diabetes prevalence among women aged 18-44 years'
 'Current smokeless tobacco use among adults aged >= 18 years'
 'Mortality from diseases of the heart'
 'Mortality from cerebrovascular disease (stroke)'
 'Hospitalization for stroke'
 'Hospitalization for heart failure among Medicare-eligible persons aged >= 65 years'
 'Hospitalization for acute myocardial infarction'
 'Mortality due to diabetes reported as any listed cause of death'
 'Mortality with diabetic ketoacidosis reported as any listed cause of death'
 'Prevalence of pre-pregnancy diabetes'
 'Amputation of a lower extremity attributable to diabetes'
 'Hospitalization with diabetes as a listed diagnosis'
 'Disability among adults aged >= 65 years'
 'Meeting aerobic physical activity guidelines among high school students'
 'Soda consumption among high school students'
 'Obesity among high school students'
 'Television viewing among high school students'
 'Computer use among high school students'
 'Overweight or obesity among high school students'
 'Healthy weight among high school students'
 'Median daily frequency of fruit consumption among high school students'
 'Median daily frequency of vegetable consumption among high school students'
 'Hospitalization for hip fracture among Medicare-eligible persons aged >= 65 years'
 'Premature mortality among adults aged 45-64 years'
 'Prevalence of 2 or more chronic conditions among Medicare-enrolled persons aged >= 65 years'
 'Preventive dental care before pregnancy'
 'Oral health services at Federally Qualified Health Centers'
 'Population served by community water systems that receive fluoridated drinking water'
 'Poverty' 'Life expectancy at age 65 years' 'Postpartum checkup'
 'Folic acid supplementation' 'Current cigarette smoking among youth'
 'Cigarette smoking before pregnancy'
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with asthma'
 'Activity limitation due to arthritis among adults aged >= 18 years who have doctor-diagnosed arthritis'
 'Local authority to regulate alcohol outlet density'
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years who smoke'
 'Amount of alcohol excise tax by beverage type (beer)'
 'Amount of alcohol excise tax by beverage type (wine)'
 'Amount of alcohol excise tax by beverage type (distilled spirits)'
 'Commercial host (dram shop) liability laws'
 'Per capita alcohol consumption among persons aged >= 14 years'
 'Proportion of older adults aged >= 65 years who are up to date on a core set of clinical preventive services'
 'Asthma prevalence among women aged 18-44 years'
 'Severe joint pain due to arthritis among adults aged >= 18 years who have doctor-diagnosed arthritis'
 'Prevalence of chronic obstructive pulmonary disease among adults >= 18'
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes'
 'Prevalence of chronic obstructive pulmonary disease among adults >= 45 years'
 'Prevalence of high blood pressure among adults aged >= 18 years with diagnosed diabetes'
 'Taking medicine for high blood pressure control among adults aged >= 18 years with high blood pressure'
 'Adults with diagnosed diabetes aged >= 18 years who have taken a diabetes self-management course'
 'Postpartum depressive symptoms' 'Pre-pregnancy hypertension'
 'Proportion of older adults aged 50-64 years who are up to date on a core set of clinical preventive services'
 'Prevalence of gestational diabetes'
 'Dental visits among children and adolescents aged 1-17 years'
 'High school completion among adults aged 18-24 years'
 'High school completion among women aged 18-44 years'
 'Health insurance coverage before pregnancy'
 'Poverty among women aged 18-44 years'
 'Participation in daily school physical education classes among high school students'
 'Live births occurring at Baby Friendly Facilities'
 'Secondary schools that allow community-sponsored use of physical activity facilities by youth outside of normal school hours'
 'Infants breastfed at 6 months'
 'Receiving formula supplementation within the first 2 days of life among breastfed infants'
 'Mean maternity practices in infant nutrition care (mPINC) score'
 'Secondary schools that allow students to purchase soda or fruit drinks'
 'Secondary schools that offer less healthy foods as competitive foods'
 'Presence of regulations pertaining to screen time in early care and education settings'
 'Secondary schools that allow students to purchase sports drinks'
 'State child care regulation supports onsite breastfeeding'
 'Influenza vaccination among noninstitutionalized adults aged >= 65 years with a history of coronary heart disease or stroke'
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with a history of coronary heart disease'
 'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with a history of coronary heart disease'
 'Prevalence of current smoking among adults >= 18 with diagnosed chronic obstructive pulmonary disease'
 'Presence of regulations pertaining to avoiding sugar in early care and education settings'
 'Number of farmers markets per 100,000 residents'
 'Census tracts with healthier food retailers within � mile of boundary'
 'Farmers markets that accept Women and Infant Children (WIC) farmers market nutrition program coupons'
 'Presence of regulations pertaining to serving fruit in early care and education settings'
 'Presence of regulations pertaining to serving vegetables in early care and education settings'
 'Farmers markets that accept Supplemental Nutrition Assistance Program (SNAP) benefits'
 'Life expectancy at birth' 'Sale of cigarette packs'
 'Amount of tobacco product excise tax'
 'Current smokeless tobacco use among youth'
 'Preventive dental visits among children and adolescents aged 1-17 years'
 'Gini Index of income inequality'
 'States that allow stronger local tobacco control and prevention laws'
 'States with strong polices that require retail licenses to sell tobacco products'
 'Proportion of the population protected by a comprehensive smoke-free policy prohibiting smoking in all indoor areas of workplaces and public places, including restaurants and bars'
 'Secondary schools that have a comprehensive tobacco-free school policy in place'
 'Percent tobacco revenue to fund at CDC recommended level'
 'Prevalence of current smoking among adults >= 45 years with diagnosed chronic obstructive pulmonary disease'
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease'
 'Influenza vaccination among noninstitutionalized adults aged 18-64 years with a history of coronary heart disease or stroke'
 'Meeting aerobic physical activity guidelines for additional and more extensive health benefits among adults aged >= 18 years'
 'Prevalence of activity limitation among adults >= 45 years with diagnosed chronic obstructive pulmonary disease'
 'Influenza vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease'
 'Prevalence of activity limitation among adults >= 18 with diagnosed chronic obstructive pulmonary disease'
 'Meeting aerobic physical activity guidelines for substantial health benefits and for muscle-strengthening activity among adults aged >= 18 years'
 'Meeting aerobic physical activity guidelines for substantial health benefits among adults aged >= 18 years'
 'Median daily frequency of vegetable consumption among adults aged >= 18 years'
 'Median daily frequency of fruit consumption among adults aged >= 18 years']
Response: [nan]
DataValueUnit: [nan '%' 'cases per 100,000' 'cases per 10,000' 'Number'
 'cases per 1,000,000' 'per 100,000' 'cases per 1,000' 'Years' '$'
 'gallons' 'per 100,000 residents' 'pack sales per capita']
DataValueType: ['Number' 'Crude Prevalence' 'Age-adjusted Rate' 'Crude Rate'
 'Average Annual Number' 'Average Annual Crude Rate'
 'Average Annual Age-adjusted Rate'
 'Adjusted by age, sex, race and ethnicity' 'Age-adjusted Prevalence'
 'Mean' 'Age-adjusted Mean' 'Median' 'Percent'
 'Local control of the regulation of alcohol outlet density' 'US Dollars'
 'Commercial host (dram shop) liability status for alcohol service'
 'Per capita alcohol consumption' 'Prevalence' 'Yes/No']
DataValue: ['30' '29.5' '22.5' ... '683.6' '103.1' '97.9']
DataValueAlt: [  30.    29.5   22.5 ... 1029.8  767.8  683.6]
DataValueFootnoteSymbol: [nan '-' '~' '&' '**' '^^^' '���' '^^' '****' '~~~~' '��' '*' '~~' '�,�'
 '�' '###' '##' '***']
DatavalueFootnote: [nan 'No data available'
 'Data not shown because of too few respondents or cases'
 'Less than 60 respondents, interpret with caution'
 'US estimate/number is based on fewer than 50 states and the District of Columbia'
 'DC was not rated for this measure because the measure addresses state versus local authority and does not apply to the District of Columbia'
 'Estimate is based on the first 3 quarters of 2015 and is not directly comparable to estimates in prior years due to changes in ICD codes'
 'State directly controlled the sale of (beer/wine/distilled spirits) at the retail and/or wholesale levels. State prices for (beer/wine/distilled spirits) combined both markups and taxes, so tax rates for this beverage type could not be determined.'
 'Sample size of denominator and/or age group for age-standardization is less than 50 or relative standard error is more than 30%'
 'The state registry opted not to present state-specific estimates for this race/ethnicity group'
 'Per capita alcohol consumption was calculated using (1) alcohol beverage sales data, either collected directly from states or provided by beverage industry sources (numerator); and (2) population data from the U.S. Census Bureau (denominator).'
 '50 States + DC: US Median'
 'A confidence interval for this location is not available because a census was used instead of a sample for their surveys'
 'Data cannot be calculated'
 'Population served by CWS exceeded the US Census state population estimate; number of persons was reduced by the ratio of the population estimate to the CWS population estimate. Complete data were not available from WFRS; state provided other information.'
 'Population served by CWS exceeded the US Census state population estimate; number of persons was reduced by the ratio of the population estimate to the CWS population estimate'
 'Median frequency (50th percentile) reported with quartiles (25th & 75th percentiles)'
 'Estimate is 0.0% because no cases were reported with this condition'
 'US Median is not available because the number of participating states is <30 (excludes states with sample size below 50 or relative standard error above 30%)']
LowConfidenceLimit: [  nan  24.9  17.  ... 382.  978.  897.2]
HighConfidenceLimit: [   nan   34.7   29.1 ...  782.5  600.4 1043.5]
StratificationCategory1: ['Race/Ethnicity' 'Gender' 'Overall']
Stratification1: ['American Indian or Alaska Native' 'Female' 'Male' 'Asian, non-Hispanic'
 'White, non-Hispanic' 'Overall' 'Hispanic' 'Black, non-Hispanic'
 'Asian or Pacific Islander' 'Multiracial, non-Hispanic'
 'Other, non-Hispanic']
StratificationCategory2: [nan]
Stratification2: [nan]
StratificationCategory3: [nan]
Stratification3: [nan]
GeoLocation: ['POINT (-120.15503132599969 44.56744942400047)'
 'POINT (-111.76381127699972 34.865970280000454)'
 'POINT (-82.40426005599966 40.06021014100048)' nan
 'POINT (-64.896335 18.335765)'
 'POINT (-86.63186076199969 32.84057112200048)'
 'POINT (-75.57774116799965 39.008830667000495)'

## Data Cleaning - Chronic Obstructive Pulmonary Disease (COPD)

In [135]:
# Begin Disease Specified Cleaning
df = df_all.copy()
df.shape #should give (1185676, 34) - same as above

(1185676, 34)

In [136]:
df.isnull().sum() #Check for missing values from entire dataset

YearStart                          0
YearEnd                            0
LocationAbbr                       0
LocationDesc                       0
DataSource                         0
Topic                              0
Question                           0
Response                     1185676
DataValueUnit                 152123
DataValueType                      0
DataValue                     378734
DataValueAlt                  381098
DataValueFootnoteSymbol       791966
DatavalueFootnote             791966
LowConfidenceLimit            503296
HighConfidenceLimit           503296
StratificationCategory1            0
Stratification1                    0
StratificationCategory2      1185676
Stratification2              1185676
StratificationCategory3      1185676
Stratification3              1185676
GeoLocation                    10166
ResponseID                   1185676
LocationID                         0
TopicID                            0
QuestionID                         0
DataValueTypeID                    0
StratificationCategoryID1          0
StratificationID1                  0
StratificationCategoryID2    1185676
StratificationID2            1185676
StratificationCategoryID3    1185676
StratificationID3            1185676
dtype: int64

In [137]:
# Drop Columns from entire dataset that are missing = Num of missing values == num of rows --> Completely empty
df = df.drop(columns=[
            'Response',  # Entire col is empty
            'StratificationCategory2', # Entire col is empty
            'Stratification2', # Entire col is empty
            'StratificationCategory3', # Entire col is empty
            'Stratification3', # Entire col is empty
            'ResponseID', # Entire col is empty
            'StratificationCategoryID2', # Entire col is empty
            'StratificationID2', # Entire col is empty
            'StratificationCategoryID3', # Entire col is empty
            'StratificationID3', # Entire col is empty
            'YearEnd', # We will use Year start instead
            'LocationAbbr', # We will use location instead
            'DataSource', #Not needed at this moment 
            'DataValueAlt', #Not needed, will use DataValue 
            'DataValueFootnoteSymbol', #Not needed at this moment 
            'DatavalueFootnote', #Not needed at this moment 
            'HighConfidenceLimit', #Not needed at this moment 
            'LowConfidenceLimit', #Not needed at this moment 
            'LocationID', # We will use Location
            'DataValueTypeID',  # Not needed 
            'TopicID' # we know this is copd
        ])
print(df.shape)
#should be (1185676, 14) - 20 cols were dropped

(1185676, 13)

In [138]:
# Now filter entier dataset for topic = 'Chronic Obstructive Pulmonary Disease'
topic = 'Chronic Obstructive Pulmonary Disease'
df_copd = df[df['Topic'] == topic]
print(df_copd.shape)
# df_copd.head()
# (1185676, 13) to (152874, 13) - about 12.9% of data is related to COPD

(152874, 13)

In [139]:
states_to_keep = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", 
                  "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", 
                  "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", 
                  "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", 
                  "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", 
                  "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

df_copd = df_copd[df_copd['LocationDesc'].isin(states_to_keep)]

In [140]:
df_copd.loc[df_copd['DataValueType'] == 'Number', 'DataValueUnit'] = 'Number'

In [141]:
df_copd.head()

,YearStart,LocationDesc,Topic,Question,DataValueUnit,DataValueType,DataValue,StratificationCategory1,Stratification1,GeoLocation,QuestionID,StratificationCategoryID1,StratificationID1
1201,2014,Alaska,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Number,Number,89,Gender,Male,POINT (-147.72205903599973 64.84507995700051),COPD1_1,GENDER,GENM
1203,2020,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Number,Number,3346,Overall,Overall,POINT (-86.63186076199969 32.84057112200048),COPD1_1,OVERALL,OVR
1204,2012,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Number,Number,252,Race/Ethnicity,"Black, non-Hispanic",POINT (-86.63186076199969 32.84057112200048),COPD1_1,RACE,BLK
1205,2015,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Number,Number,1617,Gender,Male,POINT (-86.63186076199969 32.84057112200048),COPD1_1,GENDER,GENM
1206,2017,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Number,Number,348,Race/Ethnicity,"Black, non-Hispanic",POINT (-86.63186076199969 32.84057112200048),COPD1_1,RACE,BLK

In [142]:
# Reset Index
df_copd.reset_index(drop=True, inplace=True)

In [143]:
# save to csv
output_dir = '/home/daniel.lien/dev/homework/data/cleaned_copd_data.csv'
df_copd.to_csv(output_dir, index=False)

#Can read in new dataset here or run from top

In [129]:
#create a working copy
df = df_copd.copy()
print(df.shape)
df.head()

(152874, 13)

,YearStart,LocationDesc,Topic,Question,DataValueUnit,DataValueType,DataValue,StratificationCategory1,Stratification1,GeoLocation,QuestionID,StratificationCategoryID1,StratificationID1
0,2014,Alaska,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Number,Number,89,Gender,Male,POINT (-147.72205903599973 64.84507995700051),COPD1_1,GENDER,GENM
1,2020,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Number,Number,3346,Overall,Overall,POINT (-86.63186076199969 32.84057112200048),COPD1_1,OVERALL,OVR
2,2012,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Number,Number,252,Race/Ethnicity,"Black, non-Hispanic",POINT (-86.63186076199969 32.84057112200048),COPD1_1,RACE,BLK
3,2015,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Number,Number,1617,Gender,Male,POINT (-86.63186076199969 32.84057112200048),COPD1_1,GENDER,GENM
4,2017,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Number,Number,348,Race/Ethnicity,"Black, non-Hispanic",POINT (-86.63186076199969 32.84057112200048),COPD1_1,RACE,BLK

In [72]:
df['DataValueType'].unique()

array(['Number', 'Age-adjusted Rate', 'Crude Rate', 'Crude Prevalence',
       'Age-adjusted Prevalence'], dtype=object)

In [74]:
# Group by Question and Question ID to Create Question Map
question_ID_map = df.groupby("Question")['QuestionID'].unique().apply(sorted).to_dict()
# pd.DataFrame([(k,v) for k, v in question_ID_map.items()], columns=['Question', 'QuestionID'])
question_df = (pd.DataFrame([(k, v) for k, ids in question_ID_map.items() for v in ids], 
                             columns=['Question', 'QuestionID'])
               .sort_values(by='QuestionID')
               .reset_index(drop=True))

# Print the DataFrame nicely
print(question_df)

                                             Question QuestionID
0   Mortality with chronic obstructive pulmonary d...    COPD1_1
1   Mortality with chronic obstructive pulmonary d...    COPD1_2
2   Prevalence of chronic obstructive pulmonary di...    COPD2_0
3   Prevalence of chronic obstructive pulmonary di...  COPD2_0_1
4   Prevalence of current smoking among adults >= ...    COPD3_0
5   Prevalence of current smoking among adults >= ...  COPD3_0_1
6   Prevalence of activity limitation among adults...    COPD4_0
7   Prevalence of activity limitation among adults...  COPD4_0_1
8   Hospitalization for chronic obstructive pulmon...    COPD5_1
9   Hospitalization for chronic obstructive pulmon...    COPD5_2
10  Hospitalization for chronic obstructive pulmon...    COPD5_3
11  Hospitalization for chronic obstructive pulmon...    COPD5_4
12  Emergency department visit rate for chronic ob...    COPD6_1
13  Emergency department visit rate for chronic ob...    COPD6_2
14  Influenza vaccination among noninstitutionaliz...    COPD7_0
15  Pneumococcal vaccination among noninstitutiona...    COPD8_0

COPD Question ID Map:

COPD1_1: Mortality with chronic obstructive pulmonary disease as underlying cause among adults aged >= 45 years

COPD1_2: Mortality with chronic obstructive pulmonary disease as underlying or contributing cause among adults aged >= 45 years

COPD2_0: Prevalence of chronic obstructive pulmonary disease among adults >= 18

COPD2_0_1: Prevalence of chronic obstructive pulmonary disease among adults >= 45 years

COPD3_0: Prevalence of current smoking among adults >= 18 with diagnosed chronic obstructive pulmonary disease

COPD3_0_1: Prevalence of current smoking among adults >= 45 years with diagnosed chronic obstructive pulmonary disease

COPD4_0: Prevalence of activity limitation among adults >= 18 with diagnosed chronic obstructive pulmonary disease

COPD4_0_1: Prevalence of activity limitation among adults >= 45 years with diagnosed chronic obstructive pulmonary disease

COPD5_1: Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis

COPD5_2: Hospitalization for chronic obstructive pulmonary disease as any diagnosis

COPD5_3: Hospitalization for chronic obstructive pulmonary disease as first-listed diagnosis among Medicare-eligible persons aged >= 65 years

COPD5_4: Hospitalization for chronic obstructive pulmonary disease as any diagnosis among Medicare-eligible persons aged >= 65 years

COPD6_1: Emergency department visit rate for chronic obstructive pulmonary disease as first-listed diagnosis

COPD6_2: Emergency department visit rate for chronic obstructive pulmonary disease as any diagnosis

COPD7_0: Influenza vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease

COPD8_0: Pneumococcal vaccination among noninstitutionalized adults aged >= 45 years with chronic obstructive pulmonary disease

In [78]:
df.isnull().sum() # we still have some missing values --> data value unit seems to be when data value type is Number

YearStart                        0
LocationDesc                     0
Topic                            0
Question                         0
DataValueUnit                28338
DataValueType                    0
DataValue                    58290
StratificationCategory1          0
Stratification1                  0
GeoLocation                   1098
QuestionID                       0
StratificationCategoryID1        0
StratificationID1                0
dtype: int64

# Handling missing values for Data Value Unit

In [79]:
#In each row, if datavaluetype == Number, then fill data value unit with Number as well 
df.loc[df['DataValueType'] == 'Number', 'DataValueUnit'] = 'Number'

In [80]:
df.isnull().sum() #Check --> Data Value unit is now filled

YearStart                        0
LocationDesc                     0
Topic                            0
Question                         0
DataValueUnit                    0
DataValueType                    0
DataValue                    58290
StratificationCategory1          0
Stratification1                  0
GeoLocation                   1098
QuestionID                       0
StratificationCategoryID1        0
StratificationID1                0
dtype: int64

## Handling Missing values for Data Value

In [82]:
# If data Value is missing, we have no option but to delete
# Total Rows: 152874, Total Missing Data Values: 58290
# percentage of missing values: 40%
# caused by : Data not shown because of too few respondents or cases (in the footnote)
df = df.dropna(subset=['DataValue']) 
df.isnull().sum()

YearStart                       0
LocationDesc                    0
Topic                           0
Question                        0
DataValueUnit                   0
DataValueType                   0
DataValue                       0
StratificationCategory1         0
Stratification1                 0
GeoLocation                  1050
QuestionID                      0
StratificationCategoryID1       0
StratificationID1               0
dtype: int64

In [94]:
#Fill GeoLocation with Missing for now to avoid error
df['GeoLocation'] = df['GeoLocation'].fillna('Missing').astype(str)

Currently ignore missing values in GeoLocation, it is uncertain if we will use GeoLocation since we have Location 

We group by states not GeoLocation

Dataset is complete and clean at this point

HANDLING STRATIFICATION

In [83]:
print(df['StratificationCategory1'].unique())
print(df['Stratification1'].unique())

['Gender' 'Overall' 'Race/Ethnicity']
['Male' 'Overall' 'Black, non-Hispanic' 'Hispanic' 'Female'
 'Asian or Pacific Islander' 'White, non-Hispanic'
 'American Indian or Alaska Native' 'Other, non-Hispanic'
 'Multiracial, non-Hispanic']

In [88]:
stratification_map = df.groupby('StratificationCategory1')['Stratification1'].unique().apply(list).to_dict()
print(stratification_map)

{'Gender': ['Male', 'Female'], 'Overall': ['Overall'], 'Race/Ethnicity': ['Black, non-Hispanic', 'Hispanic', 'Asian or Pacific Islander', 'White, non-Hispanic', 'American Indian or Alaska Native', 'Other, non-Hispanic', 'Multiracial, non-Hispanic']}

In [96]:
df.dtypes

YearStart                     int64
LocationDesc                 object
Topic                        object
Question                     object
DataValueUnit                object
DataValueType                object
DataValue                    object
StratificationCategory1      object
Stratification1              object
GeoLocation                  object
QuestionID                   object
StratificationCategoryID1    object
StratificationID1            object
dtype: object

In [97]:
# Convert DataValue to numeric, forcing errors to NaN if they exist
df['DataValue'] = pd.to_numeric(df['DataValue'], errors='coerce')

In [98]:
# Check for NaN or non-numeric values in DataValue
print(df[df['DataValue'].isna()])  # Displays rows where DataValue is NaN

Empty DataFrame
Columns: [YearStart, LocationDesc, Topic, Question, DataValueUnit, DataValueType, DataValue, StratificationCategory1, Stratification1, GeoLocation, QuestionID, StratificationCategoryID1, StratificationID1]
Index: []

In [99]:
# Check updated data types
print(df.dtypes)

YearStart                      int64
LocationDesc                  object
Topic                         object
Question                      object
DataValueUnit                 object
DataValueType                 object
DataValue                    float64
StratificationCategory1       object
Stratification1               object
GeoLocation                   object
QuestionID                    object
StratificationCategoryID1     object
StratificationID1             object
dtype: object

In [100]:
df_pivot = df.pivot_table(
    index=['LocationDesc', 'YearStart', 'Question'], 
    columns=['StratificationCategory1', 'Stratification1'], 
    values='DataValue'
)

# Flatten MultiIndex columns
df_pivot.columns = ['_'.join(map(str, col)).strip() for col in df_pivot.columns]


# Reset index to turn MultiIndex back into a flat DataFrame
df_pivot = df_pivot.reset_index()

# Display final table
print(df_pivot)

     LocationDesc  YearStart  \
0         Alabama       2010
1         Alabama       2010
2         Alabama       2010
3         Alabama       2010
4         Alabama       2011
...           ...        ...
6970      Wyoming       2021
6971      Wyoming       2021
6972      Wyoming       2021
6973      Wyoming       2021
6974      Wyoming       2021

                                               Question  Gender_Female  \
0     Hospitalization for chronic obstructive pulmon...    7795.610000
1     Hospitalization for chronic obstructive pulmon...    1720.316667
2     Mortality with chronic obstructive pulmonary d...     546.100000
3     Mortality with chronic obstructive pulmonary d...     893.500000
4     Hospitalization for chronic obstructive pulmon...    9112.750000
...                                                 ...            ...
6970  Pneumococcal vaccination among noninstitutiona...      74.650000
6971  Prevalence of chronic obstructive pulmonary di...       6.400000
6972  Prevalence of chronic obstructive pulmonary di...      10.400000
6973  Prevalence of current smoking among adults >= ...      44.400000
6974  Prevalence of current smoking among adults >= ...      44.200000

      Gender_Male  Overall_Overall  \
0     7378.213333     15109.730000
1     1377.523333      3085.120000
2      578.233333      1020.200000
3     1038.933333      1752.700000
4     8700.130000     17739.633333
...           ...              ...
6970    67.100000        71.300000
6971     5.800000         6.050000
6972     9.800000        10.050000
6973    28.100000        37.250000
6974    30.100000        37.300000

      Race/Ethnicity_American Indian or Alaska Native  \
0                                          141.926667
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                          173.620000
...                                               ...
6970                                              NaN
6971                                              NaN
6972                                              NaN
6973                                              NaN
6974                                              NaN

      Race/Ethnicity_Asian or Pacific Islander  \
0                                    28.936667
1                                          NaN
2                                          NaN
3                                          NaN
4                                    33.866667
...                                        ...
6970                                       NaN
6971                                       NaN
6972                                       NaN
6973                                       NaN
6974                                       NaN

      Race/Ethnicity_Black, non-Hispanic  Race/Ethnicity_Hispanic  \
0                            1893.670000                      NaN
1                             404.950000                      NaN
2                             130.333333                      NaN
3                             260.766667                      NaN
4                            2356.710000                      NaN
...                                  ...                      ...
6970                                 NaN                      NaN
6971                                 NaN                      8.4
6972                                 NaN                     12.4
6973                                 NaN                      NaN
6974                                 NaN                      NaN

      Race/Ethnicity_Multiracial, non-Hispanic  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
...                                        ...
6970                                       NaN
6971                                       NaN
6972                                       NaN
6973                                       NaN
6974                                       NaN

      Race/Ethnicity_Other, non-Hispanic  Race/Ethnicity_White, non-Hispanic
0                                    NaN                        13175.916667
1                                    NaN                         2671.143333
2                                    NaN                          946.800000
3                                    NaN                         1598.366667
4                                    NaN                        15316.623333
...                                  ...                                 ...
6970                                 NaN                           70.950000
6971                                 NaN                            5.800000
6972                                 NaN                            9.850000
6973                                 NaN                           36.700000
6974                                 NaN                           36.100000

[6975 rows x 13 columns]

In [102]:
df_pivot.head()

,LocationDesc,YearStart,Question,Gender_Female,Gender_Male,Overall_Overall,Race/Ethnicity_American Indian or Alaska Native,Race/Ethnicity_Asian or Pacific Islander,"Race/Ethnicity_Black, non-Hispanic",Race/Ethnicity_Hispanic,"Race/Ethnicity_Multiracial, non-Hispanic","Race/Ethnicity_Other, non-Hispanic","Race/Ethnicity_White, non-Hispanic"
0,Alabama,2010,Hospitalization for chronic obstructive pulmon...,7795.610000,7378.213333,15109.730000,141.926667,28.936667,1893.670000,NaN,NaN,NaN,13175.916667
1,Alabama,2010,Hospitalization for chronic obstructive pulmon...,1720.316667,1377.523333,3085.120000,NaN,NaN,404.950000,NaN,NaN,NaN,2671.143333
2,Alabama,2010,Mortality with chronic obstructive pulmonary d...,546.100000,578.233333,1020.200000,NaN,NaN,130.333333,NaN,NaN,NaN,946.800000
3,Alabama,2010,Mortality with chronic obstructive pulmonary d...,893.500000,1038.933333,1752.700000,NaN,NaN,260.766667,NaN,NaN,NaN,1598.366667
4,Alabama,2011,Hospitalization for chronic obstructive pulmon...,9112.750000,8700.130000,17739.633333,173.620000,33.866667,2356.710000,NaN,NaN,NaN,15316.623333

In [75]:
question_value_dict = df.groupby('Question')['DataValueType'].unique().apply(list).to_dict()

pd.DataFrame([(k, v) for k, v in question_value_dict.items()], columns=['Question', 'DataValueTypes'])

,Question,DataValueTypes
0,Emergency department visit rate for chronic ob...,"[Number, Crude Rate, Age-adjusted Rate]"
1,Emergency department visit rate for chronic ob...,"[Number, Age-adjusted Rate, Crude Rate]"
2,Hospitalization for chronic obstructive pulmon...,"[Number, Age-adjusted Rate, Crude Rate]"
3,Hospitalization for chronic obstructive pulmon...,"[Age-adjusted Rate, Crude Rate, Number]"
4,Hospitalization for chronic obstructive pulmon...,"[Number, Crude Rate, Age-adjusted Rate]"
5,Hospitalization for chronic obstructive pulmon...,"[Number, Age-adjusted Rate, Crude Rate]"
6,Influenza vaccination among noninstitutionaliz...,"[Age-adjusted Prevalence, Crude Prevalence]"
7,Mortality with chronic obstructive pulmonary d...,"[Number, Age-adjusted Rate, Crude Rate]"
8,Mortality with chronic obstructive pulmonary d...,"[Number, Age-adjusted Rate, Crude Rate]"
9,Pneumococcal vaccination among noninstitutiona...,"[Crude Prevalence, Age-adjusted Prevalence]"
10,Prevalence of activity limitation among adults...,"[Crude Prevalence, Age-adjusted Prevalence]"
11,Prevalence of activity limitation among adults...,"[Crude Prevalence, Age-adjusted Prevalence]"
12,Prevalence of chronic obstructive pulmonary di...,"[Crude Prevalence, Age-adjusted Prevalence]"
13,Prevalence of chronic obstructive pulmonary di...,"[Age-adjusted Prevalence, Crude Prevalence]"
14,Prevalence of current smoking among adults >= ...,"[Age-adjusted Prevalence, Crude Prevalence]"
15,Prevalence of current smoking among adults >= ...,"[Crude Prevalence, Age-adjusted Prevalence]"

Pivot Table here

In [62]:
pivot_df = df.pivot_table(
    index=["YearStart", "LocationDesc", "Topic", "Question", "DataValueType", "DataValueUnit"], 
    columns="Stratification1",
    values="DataValue",
    aggfunc="mean"  # Adjust as needed
).reset_index()

pivot_df.head()

Stratification1,YearStart,LocationDesc,Topic,Question,DataValueType,DataValueUnit,American Indian or Alaska Native,Asian or Pacific Islander,"Black, non-Hispanic",Female,Hispanic,Male,"Multiracial, non-Hispanic","Other, non-Hispanic",Overall,"White, non-Hispanic"
0,2010,Alabama,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,Age-adjusted Rate,"cases per 1,000",182.7,31.73,75.03,81.25,NaN,108.51,NaN,NaN,92.02,95.23
1,2010,Alabama,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,Crude Rate,"cases per 1,000",178.08,26.08,73.98,81.58,NaN,104.13,NaN,NaN,91.17,94.52
2,2010,Alabama,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,Age-adjusted Rate,"cases per 1,000",NaN,NaN,16.03,17.95,NaN,20.13,NaN,NaN,18.75,19.27
3,2010,Alabama,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,Crude Rate,"cases per 1,000",NaN,NaN,15.82,18.0,NaN,19.44,NaN,NaN,18.61,19.16
4,2010,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,Age-adjusted Rate,"cases per 100,000",NaN,NaN,76.3,129.2,NaN,192.1,NaN,NaN,153.1,173.4

In [63]:
df_filtered = df[df["DataValueType"] == "Crude Rate"]  # Change for other types
pivot_df_crude = df_filtered.pivot_table(
    index=["YearStart", "LocationDesc", "Topic", "Question"], 
    columns="Stratification1",
    values="DataValue",
    aggfunc="mean"
).reset_index()
pivot_df_crude.head()

Stratification1,YearStart,LocationDesc,Topic,Question,American Indian or Alaska Native,Asian or Pacific Islander,"Black, non-Hispanic",Female,Hispanic,Male,Overall,"White, non-Hispanic"
0,2010,Alabama,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,178.08,26.08,73.98,81.58,NaN,104.13,91.17,94.52
1,2010,Alabama,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,NaN,NaN,15.82,18.0,NaN,19.44,18.61,19.16
2,2010,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,NaN,NaN,59.7,132.1,NaN,154.6,142.5,171.0
3,2010,Alabama,Chronic Obstructive Pulmonary Disease,Mortality with chronic obstructive pulmonary d...,NaN,NaN,120.1,216.2,NaN,278.3,244.9,288.7
4,2010,Alaska,Chronic Obstructive Pulmonary Disease,Hospitalization for chronic obstructive pulmon...,64.4,22.79,22.05,39.81,NaN,36.66,38.25,35.0