In [18]:
import pandas as pd

In [19]:
median_income = '/home/daniel.lien/dev/homework/data/h08.xlsx'

In [20]:
df = pd.read_excel(median_income, skiprows=7)

In [21]:
#pandas automatically handled multi index 
df.columns = df.columns.map(str)
df = df.loc[:, ~df.columns.str.contains('^Unnamed: ')]

In [22]:
years_to_drop = ['2017 (40)', '2013 (39)']
df = df.drop(columns=years_to_drop)

In [23]:
import re
def extract_year(col):
    match = re.search(r'\b(19|20)\d{2}\b', str(col))
    return match.group(0) if match else col

df.columns = [extract_year(col) for col in df.columns]

In [24]:
df.columns

Index(['State', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016',
       '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007',
       '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999', '1998',
       '1997', '1996', '1995', '1994', '1993', '1992', '1991', '1990', '1989',
       '1988', '1987', '1986', '1985', '1984'],
      dtype='object')

In [25]:
#Drop
years_to_keep = [str(year) for year in range(2011,2021)]
#my 2013 is weird and 2020 is weird 
columns_to_keep = ['State'] + years_to_keep if 'State' in df.columns else years_to_keep
df = df[columns_to_keep]
df.head()

,State,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,NaN,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income,Median income
1,United States,50050,51020,51940,53660,56520,59040,61370,63180,68700,68010
2,Alabama,42590,43460,41380,42280,44510,47220,51110,49940,56200,54690
3,Alaska,57430,63650,61140,67630,75110,75720,72230,68730,78390,74750
4,Arizona,48620,47040,50600,49250,52250,57100,61130,62280,70670,67090

In [26]:
df.columns

Index(['State', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020'],
      dtype='object')

In [27]:
df = df.drop(index=0)
df.head()

,State,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,United States,50050,51020,51940,53660,56520,59040,61370,63180,68700,68010
2,Alabama,42590,43460,41380,42280,44510,47220,51110,49940,56200,54690
3,Alaska,57430,63650,61140,67630,75110,75720,72230,68730,78390,74750
4,Arizona,48620,47040,50600,49250,52250,57100,61130,62280,70670,67090
5,Arkansas,41300,39020,39920,44920,42800,45910,48830,49780,54540,50780

In [28]:
# Drop rows where 'State' is 'USA' or 'District of Columbia'
df = df[~df['State'].isin(['United States', 'District of Columbia'])]

df.head()

,State,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
2,Alabama,42590,43460,41380,42280,44510,47220,51110,49940,56200,54690
3,Alaska,57430,63650,61140,67630,75110,75720,72230,68730,78390,74750
4,Arizona,48620,47040,50600,49250,52250,57100,61130,62280,70670,67090
5,Arkansas,41300,39020,39920,44920,42800,45910,48830,49780,54540,50780
6,California,53370,57020,57530,60490,63640,66640,69760,70490,78100,77650

In [29]:
# Only keep the first half, take first 51 rows
df = df.iloc[:50]
df.shape

(50, 11)

In [30]:
df.columns

Index(['State', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020'],
      dtype='object')

In [31]:
df_long = df.melt(id_vars='State', var_name='Year', value_name='Median_Income')

In [32]:

df_long.head()

        State  Year Median_Income
0     Alabama  2011         42590
1      Alaska  2011         57430
2     Arizona  2011         48620
3    Arkansas  2011         41300
4  California  2011         53370

In [33]:
df_long.columns

Index(['State', 'Year', 'Median_Income'], dtype='object')

In [34]:
output_dir = '/home/daniel.lien/dev/homework/data/medianincome_temp2.csv'
df_long.to_csv(output_dir, index=False)